#	Authored: Max Pfeiffer - 2018
#
#	Reads .csv files generated by the get_common.py script and further refines the 
#	list of common ids and/or messages  
#
# 	Software is free and open to anyone who wishes to use it under the GNU public license 
#
#	Usage: python get_common.py "filename_one.csv" "filename_two.csv"
#
#	Result:	common_ids.csv and common_msgs.csv in the working directory.
#
#!/usr/bin/python